#!/usr/bin/env python
# .*. coding: UTF-8 .*.

import os
import re
import sys
import mantis
from optparse import OptionParser

MANTIS_GERRIT_OPENED_FIELD_ID = 1
MANTIS_GERRIT_ABANDONED_FIELD_ID = 2
MANTIS_GERRIT_MERGED_FIELD_ID = 3

def main():
   usage = 'Usage: %prog --change <change id> --change-url <change url> --change-owner <change owner> --project <project name> --branch <branch> --topic <topic> --submitter <submitter> --commit <sha1> --newrev <sha1>'
   parser = OptionParser(usage)
   parser.set_defaults(keepSource=False)

   parser.add_option("--change", dest="changeId", help="Change Id")
   parser.add_option("--change-url", dest="changeUrl", help="Change URL")
   parser.add_option("--change-owner", dest="changeOwner", help="Change Owner")
   parser.add_option("--project", dest="projectName", help="Project Name")
   parser.add_option("--branch", dest="branchName", help="Branch Name")
   parser.add_option("--topic", dest="topic", help="Topic")
   parser.add_option("--submitter", dest="submitter", help="Submitter Name")
   parser.add_option("--commit", dest="commit", help="Commit Sha1 Id")
   parser.add_option("--newrev", dest="newrev", help="New Revision")

   (options, args) = parser.parse_args()

   try:
      GIT_DIR = os.environ['GIT_DIR']
   except OSError:
      print "GIT_DIR env var not found!"
      sys.exit(1)

   # GET COMMIT MESSAGE TO RETRIEVE BUG ID
   commit_message = mantis.get_commit_message(GIT_DIR,options.commit)

   # CHECK IF BUD ID IS ON COMMIT MESSAGE
   if re.match("[Bb][Uu][Gg][ ]*[0-9]+",commit_message) == None and re.match("[Rr]evert [\"]*[Bb][Uu][Gg][ ]*[0-9]+",commit_message) == None:
      print "Ops,\nCommit message does not contain bug id identification!\nPlease change your commit message to start with:\n\tBug <bug number> - Commit message\nUse: git commit --amend\n"
      sys.exit(1)

   # GET BUGID NUMBER
   match = re.search("[Bb][Uu][Gg][ ]*[0-9]+",commit_message)
   if match is None :
      print "Ops,\nBug ID not found in commit message!\nPlease fix it running:\ngit commit --amend\n"
      sys.exit(1)
   bugid = commit_message[match.start():match.end()]
   bugid = re.sub('[^0-9]*','',bugid.split()[1])

   # REMOVE CHANGE URL FROM GERRIT CUSTOM FIELD
   if not mantis.remove_gerrit_change_url(bugid,MANTIS_GERRIT_OPENED_FIELD_ID,options.changeUrl):
      print "Ops,\nWe found an issue trying to remove gerrit url from \"Gerrit Opened\" custom field for Bug ticket " + bugid + "!"
      sys.exit(1)

   # ADD CHANGE URL INTO MERGED CUSTOM FIELD
   if mantis.add_gerrit_change_url(bugid,MANTIS_GERRIT_MERGED_FIELD_ID,options.changeUrl):
      note = 'Following fix was merged: ' + options.changeUrl
      mantis.add_gerrit_note(bugid,note)
   else:
      print "Ops,\nWe found an issue trying to add gerrit link into \"Gerrits Merged\" custom field for Bug ticket " + bugid + "!"
      sys.exit(1)

   # GO AHEAD AND ACCEPT FIX
   sys.exit(0)

if __name__ == '__main__':
   main()
