#!/usr/bin/env python
# .*. coding: UTF-8 .*.

import os
import re
import sys
import mantis
from optparse import OptionParser

MANTIS_GERRIT_FIELD_ID = 1
MANTIS_ABANDONED_FIELD_ID = 2

def main():
   usage = 'Usage: %prog --change <change id> --change-url <change url> --change-owner <change owner> --project <project name> --branch <branch> --topic <topic> --restorer <restorer> --commit <sha1> --reason <reason>'
   parser = OptionParser(usage)
   parser.set_defaults(keepSource=False)

   parser.add_option("--change", dest="changeId", help="Change Id")
   parser.add_option("--change-url", dest="changeUrl", help="Change URL")
   parser.add_option("--change-owner", dest="changeOwner", help="Change Owner")
   parser.add_option("--project", dest="projectName", help="Project Name")
   parser.add_option("--branch", dest="branchName", help="Branch Name")
   parser.add_option("--topic", dest="topic", help="Topic")
   parser.add_option("--restorer", dest="restorer", help="Restorer Name")
   parser.add_option("--commit", dest="commit", help="Commit Sha1 Id")
   parser.add_option("--reason", dest="reason", help="Reason")

   (options, args) = parser.parse_args()

   try:
      GIT_DIR = os.environ['GIT_DIR']
   except OSError:
      print "GIT_DIR env var not found for Bug ticket " + id + "!"
      sys.exit(1)

   # GET COMMIT MESSAGE TO RETRIEVE BUG ID
   commit_message = mantis.get_commit_message(GIT_DIR,options.commit)
   bugid = re.sub('[^0-9]*','',commit_message.split()[1])

   if bugid == '':
      print "Bug ID number not found ar commit message for Bug ticket " + id + "!"
      sys.exit(1)

   # REMOVE CHANGE URL FROM ABANDONED CUSTOM FIELD
   if not mantis.remove_gerrit_change_url(bugid,MANTIS_ABANDONED_FIELD_ID,options.changeUrl):
      print "Ops,\nWe found an issue trying to remove gerrit url from \"Abandoned\" custom field at Bug ticket " + id + "!"
      sys.exit(1)

   # ADD CHANGE URL INTO GERRIT CUSTOM FIELD
   if mantis.add_gerrit_change_url(bugid,MANTIS_GERRIT_FIELD_ID,options.changeUrl):
      note = 'Following fix was restored: ' + options.changeUrl + '\nReason: ' + options.reason + '\nRestored by: ' + options.restorer
      mantis.add_gerrit_note(bugid,note)
   else:
      print "Ops,\nWe found an issue trying to add gerrit link into \"Gerrit\" custom field at Bug ticket " + id + "!"
      sys.exit(1)

   # GO AHEAD AND ACCEPT FIX
   sys.exit(0)

if __name__ == '__main__':
   main()

