#!/usr/bin/env python
# .*. coding: UTF-8 .*.

import os
import re
import sys
import mantis
from optparse import OptionParser

MANTIS_GERRIT_FIELD_ID = 1
MANTIS_ABANDONED_FIELD_ID = 2

def main():
   usage = 'Usage: %prog --change <change id> --is-draft <boolean> --kind <change kind> --change-url <change url> --change-owner <change owner> --project <project name> --branch <branch> --topic <topic> --uploader <uploader> --commit <sha1> --patchset <patchset id>'
   parser = OptionParser(usage)
   parser.set_defaults(keepSource=False)

   parser.add_option("--change", dest="changeId", help="Change Id")
   parser.add_option("--is-draft", dest="isDraft", help="True if Change is Draft")
   parser.add_option("--kind", dest="changeKind", help="Change Kind")
   parser.add_option("--change-url", dest="changeUrl", help="Change URL")
   parser.add_option("--change-owner", dest="changeOwner", help="Change Owner")
   parser.add_option("--project", dest="projectName", help="Project Name")
   parser.add_option("--branch", dest="branchName", help="Branch Name")
   parser.add_option("--topic", dest="topic", help="Topic")
   parser.add_option("--uploader", dest="uploader", help="Uploader Name")
   parser.add_option("--commit", dest="commit", help="Commit Sha1 Id")
   parser.add_option("--patchset", dest="patchsetId", help="Patchset Id")

   (options, args) = parser.parse_args()

   try:
      GIT_DIR = os.environ['GIT_DIR']
   except OSError:
      print "GIT_DIR env var not found!"
      sys.exit(1)

   # GET COMMIT MESSAGE TO RETRIEVE BUG ID
   commit_message = mantis.get_commit_message(GIT_DIR,options.commit)

   if re.match("[Bb][Uu][Gg][ ]*[0-9]+",commit_message) == None:
      print "Ops,\nCommit message does not contain bug id identification!\nPlease change your commit message to start with:\n\tBug <bug number> - Commit message\nUse: git commit --amend\n"
      sys.exit(1)

   bugid = re.sub('[^0-9]*','',commit_message.split()[1])

   # ADD CHANGE URL INTO GERRIT CUSTOM FIELD
   if mantis.add_gerrit_change_url(bugid,MANTIS_GERRIT_FIELD_ID,options.changeUrl):
      note = 'New fix is now available at: ' + options.changeUrl + '\nUploader: ' + options.uploader
      mantis.add_gerrit_note(bugid,note)
   else:
      print "Ops,\nWe found an issue trying to add gerrit link into \"Abandoned\" custom field at Bug ticket " + bugid + "!"
      sys.exit(1)

   # GO AHEAD AND ACCEPT FIX
   sys.exit(0)

if __name__ == '__main__':
   main()

